-- ─── Phase 1.1 Storage & RPC Security ────────────────────────────────────────
--
-- Three fixes:
--   1. Storage RLS — replace bucket-only policies with per-user-path policies.
--      BEFORE: any authenticated user could read/update/delete/list any other
--              user's objects in the 'documents' bucket.
--      AFTER:  each user's JWT scopes them to only their own path prefixes.
--
--   2. sync_blueprint_draft_fields RPC — add authorization check.
--      BEFORE: SECURITY DEFINER with no ownership validation — any caller could
--              delete and overwrite another user's blueprint draft fields.
--      AFTER:  function raises insufficient_privilege unless auth.uid() owns
--              the target contract_template.
--
--   3. signing_sessions.completion_claimed_at — add column for atomic completion
--      claiming so two concurrent callers cannot both generate the completed PDF.
--
-- Safe to re-run (DROP … IF EXISTS / ADD … IF NOT EXISTS pattern).
-- Service role bypasses RLS — no server-side application routes are affected.
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── 1. Storage path ownership model ─────────────────────────────────────────
--
-- Active path families and their owner segment:
--
--   {userId}/{timestamp}_{filename}           — user-uploaded docs
--   contract-templates/{userId}/{...}         — blueprint template PDFs
--   signed/{userId}/{sessionId}_completed_... — completed signed PDFs
--   certificates/{userId}/{sessionId}_cert_.. — signing certificates
--
-- Rule: authenticated user may only access objects in their own path prefix.
-- Service role (used by all server API routes) bypasses RLS unconditionally.
-- Signed URLs generated by service role are pre-authorised time-limited tokens
-- and do not pass through storage RLS.

-- ── 1a. SELECT ────────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "documents_select" ON storage.objects;
CREATE POLICY "documents_select" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'documents'
    AND (
      -- user-uploaded: {userId}/...
      name LIKE auth.uid()::text || '/%'
      -- contract templates: contract-templates/{userId}/...
      OR name LIKE 'contract-templates/' || auth.uid()::text || '/%'
      -- completed signed PDFs: signed/{userId}/...
      OR name LIKE 'signed/' || auth.uid()::text || '/%'
      -- signing certificates: certificates/{userId}/...
      OR name LIKE 'certificates/' || auth.uid()::text || '/%'
    )
  );

-- ── 1b. INSERT ───────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "documents_insert" ON storage.objects;
CREATE POLICY "documents_insert" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'documents'
    AND (
      name LIKE auth.uid()::text || '/%'
      OR name LIKE 'contract-templates/' || auth.uid()::text || '/%'
      OR name LIKE 'signed/' || auth.uid()::text || '/%'
      OR name LIKE 'certificates/' || auth.uid()::text || '/%'
    )
  );

-- ── 1c. UPDATE ───────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "documents_update" ON storage.objects;
CREATE POLICY "documents_update" ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'documents'
    AND (
      name LIKE auth.uid()::text || '/%'
      OR name LIKE 'contract-templates/' || auth.uid()::text || '/%'
      OR name LIKE 'signed/' || auth.uid()::text || '/%'
      OR name LIKE 'certificates/' || auth.uid()::text || '/%'
    )
  )
  WITH CHECK (
    bucket_id = 'documents'
    AND (
      name LIKE auth.uid()::text || '/%'
      OR name LIKE 'contract-templates/' || auth.uid()::text || '/%'
      OR name LIKE 'signed/' || auth.uid()::text || '/%'
      OR name LIKE 'certificates/' || auth.uid()::text || '/%'
    )
  );

-- ── 1d. DELETE ───────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "documents_delete" ON storage.objects;
CREATE POLICY "documents_delete" ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'documents'
    AND (
      name LIKE auth.uid()::text || '/%'
      OR name LIKE 'contract-templates/' || auth.uid()::text || '/%'
      OR name LIKE 'signed/' || auth.uid()::text || '/%'
      OR name LIKE 'certificates/' || auth.uid()::text || '/%'
    )
  );

-- ─── 2. RPC authorization — sync_blueprint_draft_fields ──────────────────────
--
-- SECURITY DEFINER bypasses table-level RLS so the function runs as the DB owner.
-- Without an explicit caller check, any authenticated user could call this RPC
-- with another user's blueprint_id and wipe their draft fields.
--
-- Fix: validate auth.uid() owns the contract_template before any DML.
-- auth.uid() is available in SECURITY DEFINER functions via the JWT GUC that
-- Supabase sets for every authenticated request (request.jwt.claims).
-- search_path is already pinned to 'public' (safe).

CREATE OR REPLACE FUNCTION sync_blueprint_draft_fields(
  p_blueprint_id  uuid,
  p_fields        jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result jsonb;
BEGIN
  -- ── Authorization guard ──────────────────────────────────────────────────
  -- The calling authenticated user must own the target contract_template.
  -- Raises insufficient_privilege (SQLSTATE 42501) if not.
  IF NOT EXISTS (
    SELECT 1
    FROM   contract_templates ct
    WHERE  ct.id = p_blueprint_id
      AND  ct.user_id = auth.uid()
  ) THEN
    RAISE EXCEPTION
      'authorization_error: caller % does not own blueprint %',
      auth.uid(), p_blueprint_id
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- ── Atomic DELETE + INSERT ───────────────────────────────────────────────
  DELETE FROM template_fields
  WHERE blueprint_id = p_blueprint_id
    AND blueprint_version_id IS NULL;

  IF jsonb_array_length(p_fields) > 0 THEN
    INSERT INTO template_fields (
      blueprint_id,
      blueprint_version_id,
      field_key,
      field_type,
      page,
      x, y, width, height,
      merge_key,
      label,
      font_size,
      sort_order,
      signer_role_id,
      required,
      ai_source,
      created_by,
      last_modified_by
    )
    SELECT
      p_blueprint_id,
      NULL,
      COALESCE((f->>'field_key')::uuid, gen_random_uuid()),
      COALESCE(f->>'field_type', 'merge_text'),
      COALESCE((f->>'page')::int, 1),
      COALESCE((f->>'x')::numeric, 0),
      COALESCE((f->>'y')::numeric, 0),
      COALESCE((f->>'width')::numeric, 0.15),
      COALESCE((f->>'height')::numeric, 0.04),
      NULLIF(f->>'merge_key', ''),
      NULLIF(f->>'label', ''),
      COALESCE((f->>'font_size')::int, 11),
      COALESCE((f->>'sort_order')::int, 0),
      NULLIF(f->>'signer_role_id', '')::uuid,
      COALESCE((f->>'required')::boolean, false),
      COALESCE(f->>'ai_source', 'manual'),
      NULLIF(f->>'created_by', '')::uuid,
      NULLIF(f->>'last_modified_by', '')::uuid
    FROM jsonb_array_elements(p_fields) AS f;
  END IF;

  SELECT jsonb_agg(row_to_json(tf)::jsonb ORDER BY tf.sort_order, tf.created_at)
  INTO v_result
  FROM template_fields tf
  WHERE tf.blueprint_id = p_blueprint_id
    AND tf.blueprint_version_id IS NULL;

  RETURN COALESCE(v_result, '[]'::jsonb);
END;
$$;

GRANT EXECUTE ON FUNCTION sync_blueprint_draft_fields(uuid, jsonb) TO authenticated, service_role;

-- ─── 3. Atomic completion claiming ───────────────────────────────────────────
--
-- Two concurrent completion calls could both read completed_pdf_path = NULL and
-- both proceed to generate + upload a PDF. The result: two completed_pdf_path
-- writes (second wins) and two documents rows inserted.
--
-- Fix: add completion_claimed_at. The completer does an atomic UPDATE that sets
-- this column only when it IS NULL and completed_pdf_path IS NULL. Postgres
-- row-level locking ensures only one concurrent UPDATE wins. Losers re-read the
-- session and either short-circuit (if completed) or abort (if in-progress).
-- A 10-minute stale-claim window allows retry after a crashed completion attempt.

ALTER TABLE signing_sessions
  ADD COLUMN IF NOT EXISTS completion_claimed_at timestamptz;
