-- ═══════════════════════════════════════════════════════════════════════════════
-- Phase 6.5 Sprint 1 — Comparables + Market Statistics Tables
--
-- Creates two tables. Zero changes to existing tables.
-- Note: market_intelligence_events (Phase 5) already exists for raw event data.
-- market_statistics (this migration) stores pre-aggregated period summaries.
-- ═══════════════════════════════════════════════════════════════════════════════


-- ── property_comparables ─────────────────────────────────────────────────────
-- Comparable properties for a subject property.
-- Generated by the comp engine and stored for the Comps tab.
-- Expires after 90 days — comp data goes stale.

CREATE TABLE IF NOT EXISTS property_comparables (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  subject_property_id uuid        NOT NULL REFERENCES properties(id) ON DELETE CASCADE,

  -- The comparable property (may or may not be in our system)
  comp_property_id    uuid        REFERENCES properties(id) ON DELETE SET NULL,
  comp_mls_number     text,
  comp_address        jsonb       NOT NULL DEFAULT '{}',
  -- { street, city, state, zip }

  relationship        text        NOT NULL DEFAULT 'closed_comp',
  -- 'active_comp' | 'closed_comp' | 'expired_comp'

  -- Key comp attributes
  list_price          numeric,
  close_price         numeric,
  sqft                integer,
  beds                smallint,
  baths               numeric,
  year_built          smallint,
  lot_sqft            integer,
  days_on_market      integer,
  price_per_sqft      numeric,
  distance_miles      numeric,
  list_date           date,
  close_date          date,

  -- CMA adjustment model (for manual CMA creation in Sprint 3+)
  adjustments         jsonb       NOT NULL DEFAULT '{}',
  -- { sqft_adj, condition_adj, location_adj, ... }
  adjusted_value      numeric,

  source              text        NOT NULL DEFAULT 'beaches-mls',
  generated_at        timestamptz NOT NULL DEFAULT now(),
  expires_at          timestamptz NOT NULL DEFAULT (now() + interval '90 days'),
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pc_subject      ON property_comparables(subject_property_id);
CREATE INDEX IF NOT EXISTS idx_pc_relationship ON property_comparables(subject_property_id, relationship);
CREATE INDEX IF NOT EXISTS idx_pc_expires      ON property_comparables(expires_at);
CREATE INDEX IF NOT EXISTS idx_pc_distance     ON property_comparables(subject_property_id, distance_miles);

ALTER TABLE property_comparables ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'property_comparables' AND policyname = 'auth users full access'
  ) THEN
    CREATE POLICY "auth users full access" ON property_comparables
      FOR ALL USING (auth.role() = 'authenticated');
  END IF;
END $$;


-- ── market_statistics ─────────────────────────────────────────────────────────
-- Pre-aggregated market statistics per geography + period.
-- market_intelligence_events (Phase 5) is the raw append-only feed.
-- market_statistics is the computed summary used by the Market tab in the UI.
--
-- market_key format:
--   zip:33101        — ZIP code market
--   city:Miami       — city market
--   county:miami-dade — county market
--   zip:33101:condo  — ZIP + property sub-type

CREATE TABLE IF NOT EXISTS market_statistics (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  market_key          text        NOT NULL,
  period_start        date        NOT NULL,
  period_end          date        NOT NULL,
  period_type         text        NOT NULL DEFAULT 'monthly',
  -- 'monthly' | 'quarterly' | 'annual'

  -- Inventory
  active_listings     integer,
  new_listings        integer,
  closed_listings     integer,
  expired_listings    integer,

  -- Pricing
  median_list_price   numeric,
  median_close_price  numeric,
  median_price_sqft   numeric,
  median_sp_lp_ratio  numeric,
  -- SP/LP = sale price / list price (1.0 = sold at list)

  -- Velocity
  median_dom          integer,
  absorption_months   numeric,
  -- months of inventory = active_listings / (closed_listings / period_days * 30)

  -- Computed context
  total_volume        numeric,
  -- sum of closed sale prices for the period

  source              text        NOT NULL DEFAULT 'computed',
  computed_at         timestamptz NOT NULL DEFAULT now(),
  created_at          timestamptz NOT NULL DEFAULT now(),

  UNIQUE (market_key, period_start, period_type)
);

CREATE INDEX IF NOT EXISTS idx_ms_market_key  ON market_statistics(market_key);
CREATE INDEX IF NOT EXISTS idx_ms_period      ON market_statistics(market_key, period_start DESC);
CREATE INDEX IF NOT EXISTS idx_ms_type        ON market_statistics(period_type, period_start DESC);

ALTER TABLE market_statistics ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'market_statistics' AND policyname = 'auth users full access'
  ) THEN
    CREATE POLICY "auth users full access" ON market_statistics
      FOR ALL USING (auth.role() = 'authenticated');
  END IF;
END $$;
